# Generated by Django 6.0.2 on 2026-02-25 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(help_text='Units reserved (1–5).', verbose_name='Quantity')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=12, verbose_name='Status')),
                ('expires_at', models.DateTimeField(help_text='UTC timestamp when this reservation expires if not converted.', verbose_name='Expires At')),
                ('extension_count', models.PositiveSmallIntegerField(default=0, help_text='Number of times the reservation has been extended (max 1).', verbose_name='Extension Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservations_reservation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('status', 'ACTIVE')), fields=['expires_at'], name='resv_active_expires_idx'), models.Index(fields=['user', 'status'], name='reservation_user_status_idx'), models.Index(fields=['variant', 'status'], name='reservation_variant_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 5)), name='resv_qty_1_to_5'), models.CheckConstraint(condition=models.Q(('extension_count__lte', 1)), name='resv_max_ext')],
            },
        ),
    ]
