# Generated by Django 6.0.2 on 2026-03-08 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('reservations', '0002_remove_reservation_resv_max_ext_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='resv_qty_1_to_5',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Units reserved (must be >= 1).', verbose_name='Quantity'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='resv_qty_gte_1'),
        ),
    ]
