# Generated by Django 6.0.2 on 2026-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_resv_qty_1_to_5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активен'), ('EXPIRED', 'Истек'), ('CONVERTED', 'Преобразован в заказ'), ('CANCELLED', 'Отменен')], db_index=True, default='ACTIVE', max_length=12, verbose_name='Status'),
        ),
    ]
