# Generated by Django 6.0.2 on 2026-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('push', 'Пуш'), ('sms', 'SMS'), ('in_app', 'В приложении')], default='in_app', max_length=20),
        ),
    ]
