# Generated by Django 6.0.2 on 2026-03-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_play_sound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='play_sound',
            field=models.BooleanField(default=True, verbose_name='Звук'),
        ),
    ]
