# Generated by Django 6.0.2 on 2026-03-14 08:51

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Бонусный баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Определяет, должен ли этот пользователь считаться активным.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Определяет, может ли пользователь входить в панель администратора.', verbose_name='Статус персонала'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Агент, пригласивший пользователя (узел MPTT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Спонсор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_turnover',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Личный оборот'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(db_index=True, editable=False, help_text='Уникальный реферальный код агента', max_length=8, unique=True, verbose_name='Реферальный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Золото')], db_index=True, default='NEW', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_turnover',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Командный оборот'),
        ),
        migrations.AlterField(
            model_name='userstatushistory',
            name='new_status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Золото')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userstatushistory',
            name='old_status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Золото')], max_length=10),
        ),
    ]
