# Generated by Django 6.0.2 on 2026-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(choices=[('PERSONAL', 'Личный'), ('TEAM', 'Командный')], default='PERSONAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='calculation_type_snapshot',
            field=models.CharField(choices=[('PERCENT', 'Процент'), ('FIXED', 'Фиксированная сумма')], default='PERCENT', max_length=10, verbose_name='Calculation Type (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('CONFIRMED', 'Подтвержден')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='mlmrule',
            name='agent_status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Золото')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mlmrule',
            name='calculation_type',
            field=models.CharField(choices=[('PERCENT', 'Процент'), ('FIXED', 'Фиксированная сумма')], default='PERCENT', help_text='PERCENT: value% of order total.  FIXED: flat amount per order.', max_length=10, verbose_name='Calculation Type'),
        ),
    ]
