# Generated by Django 6.0.2 on 2026-03-22 16:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0003_alter_bonus_bonus_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='applied_value_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Applied Value (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='percent_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='mlmrule',
            name='calculation_type',
            field=models.CharField(choices=[('PERCENT', 'Процент'), ('FIXED', 'Фиксированная сумма')], default='PERCENT', help_text='Процент: значение в % от суммы заказа. Фиксированная сумма: сумма за заказ.', max_length=10, verbose_name='Calculation Type'),
        ),
        migrations.AlterField(
            model_name='mlmrule',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Value'),
        ),
    ]
