# Generated by Django 6.0.2 on 2026-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('RESERVED', 'Забронирован'), ('CONFIRMED', 'Подтвержден'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], db_index=True, default='CREATED', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderlifecyclelog',
            name='from_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Создан'), ('RESERVED', 'Забронирован'), ('CONFIRMED', 'Подтвержден'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderlifecyclelog',
            name='to_status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('RESERVED', 'Забронирован'), ('CONFIRMED', 'Подтвержден'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], max_length=12),
        ),
    ]
