# Generated by Django 6.0.2 on 2026-03-16 20:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_orderdelivery_status'),
        ('orders', '0003_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(help_text='Обязательно — адрес, куда доставляется заказ при оплате при получении.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.deliveryaddress', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Снимок стоимости доставки на момент оформления заказа.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Сумма позиций заказа (количество × цена каждой позиции).', max_digits=14),
        ),
    ]
