# Generated by Django 6.0.2 on 2026-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_orderdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
