# Generated by Django 6.0.2 on 2026-02-25 16:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_size', models.PositiveIntegerField(default=0, verbose_name='Team Size')),
                ('team_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Team Sales')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_stats', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Network Stats',
                'verbose_name_plural': 'Network Stats',
                'db_table': 'mlm_networkstats',
            },
        ),
        migrations.CreateModel(
            name='StatusThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], db_index=True, max_length=10, unique=True, verbose_name='Status')),
                ('min_personal_turnover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cumulative personal sales to reach this status.', max_digits=14, verbose_name='Min Personal Turnover')),
                ('min_team_turnover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cumulative downline sales to reach this status.', max_digits=14, verbose_name='Min Team Turnover')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status Threshold',
                'verbose_name_plural': 'Status Thresholds',
                'db_table': 'mlm_status_threshold',
                'ordering': ['min_personal_turnover'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_personal_turnover__gte', 0)), name='threshold_personal_gte_0'), models.CheckConstraint(condition=models.Q(('min_team_turnover__gte', 0)), name='threshold_team_gte_0')],
            },
        ),
    ]
