# Generated by Django 6.0.2 on 2026-03-22 16:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusthreshold',
            name='min_personal_turnover',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Min Personal Turnover'),
        ),
        migrations.AlterField(
            model_name='statusthreshold',
            name='min_team_turnover',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Min Team Turnover'),
        ),
        migrations.AlterField(
            model_name='statusthreshold',
            name='status',
            field=models.CharField(choices=[('BRONZE', 'Бронза'), ('SILVER', 'Серебро'), ('GOLD', 'Золото')], db_index=True, max_length=10, unique=True, verbose_name='Status'),
        ),
    ]
