# Generated by Django 6.0.2 on 2026-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_alter_withdrawal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('APPROVED', 'Подтверждена'), ('REJECTED', 'Отклонена')], db_index=True, default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
