# Generated by Django 6.0.2 on 2026-03-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_image_productvariant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='TJS', max_length=3),
        ),
    ]
