# Generated by Django 6.0.2 on 2026-03-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, help_text='Можно выбрать несколько характеристик для карточки товара.', related_name='products', to='products.productattributevalue', verbose_name='Характеристики товара'),
        ),
    ]
